version: '2.1'
orbs:
  python: circleci/python@2.1.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - run:
          command: make test
          name: Test
workflows:
  main:
    jobs:
      - build
