version: 2.1

parameters:
  cachever:
    type: string
    default: "v1"

executors:
  python:
    docker:
      - image: python:3.9

jobs:
  build:
    executor: python
    steps:
      - checkout
      - restore_cache:
          name: Restore venv
          keys:
            - << pipeline.parameters.cachever >>-venv-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install
          command: make venv
      - save_cache:
          name: Save venv
          key: << pipeline.parameters.cachever >>-venv-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
          paths:
            - /root/project/.venv
      - run:
          name: Test
          command: make test

workflows:
  main:
    jobs:
      - build
